const cameras = [
  {
    name: "DSLR Cameras",
    price: "720",
    des: "DSLR camera has a unique feature called reflex design scheme where light travels through the",
    img: "https://i.ibb.co/qgwSwD1/the-best-is-yet-to-come-framed-poster.png",
    status: "pendding",
  },
  {
    name: "Canon",
    price: "980",
    des: "Global website of Canon Inc., a leader in the fields of professional and consumer imaging",
    img: "https://i.ibb.co/b25HyKj/the-adventure-begins-framed-poster.png",
    status: "pendding",
  },
  {
    name: "Nikon",
    price: "1200",
    des: "Nikon cameras have been trusted by photographers and picture takers of",
    img: "https://i.ibb.co/zSRJP4b/hummingbird-printed-t-shirt-1.png",
    status: "pendding",
  },
  {
    name: "Pentax",
    price: "1380",
    des: "Pentax is one of the few camera manufacturers still producing medium format cameras. As of",
    img: "https://i.ibb.co/TrwgPdC/brown-bear-printed-sweater.png",
    status: "pendding",
  },
  {
    name: "Sony",
    price: "760",
    des: "Discover the range of Sony cameras, lenses and accessories, and capture your favourite",
    img: "https://i.ibb.co/BNn0dYx/brown-bear-printed-sweater-4.png",
    status: "pendding",
  },
  {
    name: "Olympus",
    price: "999",
    des: "Break Free with Olympus. Explore small, lightweight, travel-ready camera and lens systems to",
    img: "https://i.ibb.co/wzyw2XB/brown-bear-printed-sweater-3.png",
    status: "pendding",
  },
  {
    name: "Fujifilm",
    price: "1120",
    des: " The central themes of the GFX & X Series are simplicity and elegance; the camera is",
    img: "https://i.ibb.co/sPGJwTf/banner-slide1.png",
    status: "pendding",
  },
  {
    name: "Gopro",
    price: "1050",
    des: "Limited to a maximum of 10 items per subscription anniversary year. ³Exchange up",
    img: "https://i.ibb.co/9ZLLMBZ/banner-slide3-1.png",
    status: "pendding",
  },
  {
    name: "Leica",
    price: "1790",
    des: "Leica Camera AG is an internationally operating, premium-segment manufacturer of cameras",
    img: "https://i.ibb.co/S6vqjmW/brown-bear-printed-sweater-1.png",
    status: "pendding",
  },
  {
    name: "Canon",
    price: "2250",
    des: "Global website of Canon Inc., a leader in the fields of professional and consumer imagin",
    img: "https://i.ibb.co/C196zsP/brown-bear-printed-sweater-2.png",
    status: "pendding",
  },
];
